# -*- coding: utf-8 -*-

ADX_DECRYPT_DIR = '\\adxToWav'
ADX_DECRYPT_WITH_SPECIAL_KEY_SCRIPT_PATH = ADX_DECRYPT_DIR + '\\特殊鍵指定デコード.bat'
ADX_SPECIAL_KEY_LIST = ADX_DECRYPT_DIR + '\\特殊鍵リスト.txt'
ADX_DECRYPT_WITH_DECRYPT_KEY_SCRIPT_PATH = ADX_DECRYPT_DIR + '\\復号鍵指定デコード.bat'
ADX_DECRYPT_KEY_LIST = ADX_DECRYPT_DIR + '\\復号鍵リスト.txt'

ACB_DECRYPT_DIR = '\\acbToHca'
ACB_DECRYPT_SCRIPT_PATH = ACB_DECRYPT_DIR + '\\afs2.exe'
ACB_DECRYPT_CUT_HEAD_SCRIPT_PATH = ACB_DECRYPT_DIR + '\\先頭をカットして展開.bat'

HCA_DECRYPT_DIR = '\\hcaToWav'
HCA_DECRYPT_MULTIFILE_SCRIPT_PATH = HCA_DECRYPT_DIR + '\\復号化.bat'
HCA_DECRYPT_SCRIPT_PATH = HCA_DECRYPT_DIR + '\\hca.exe'
HCA_DECRYPT_KEY_LIST = HCA_DECRYPT_DIR + '\\復号鍵リスト.txt'
