# -*- coding: utf-8 -*-

ADX_TO_WAV_DIR = '\\adxToWav'
ADX_TO_WAV_WITH_SPECIAL_KEY_SCRIPT_PATH = ADX_TO_WAV_DIR + '\\特殊鍵指定デコード.bat'
ADX_TO_WAV_SPECIAL_KEY_LIST = ADX_TO_WAV_DIR + '\\特殊鍵リスト.txt'
ADX_TO_WAV_WITH_DECRYPT_KEY_SCRIPT_PATH = ADX_TO_WAV_DIR + '\\復号鍵指定デコード.bat'
ADX_TO_WAV_KEY_LIST = ADX_TO_WAV_DIR + '\\復号鍵リスト.txt'

ACB_TO_HCA_DIR = '\\acbToHca'
ACB_TO_HCA_SCRIPT_PATH = ACB_TO_HCA_DIR + '\\afs2.exe'
ACB_TO_HCA_CUT_HEAD_SCRIPT_PATH = ACB_TO_HCA_DIR + '\\先頭をカットして展開.bat'

HCA_TO_WAV_DIR = '\\hcaToWav'
HCA_TO_WAV_MULTIFILE_SCRIPT_PATH = HCA_TO_WAV_DIR + '\\復号化.bat'
HCA_TO_WAV_SCRIPT_PATH = HCA_TO_WAV_DIR + '\\hca.exe'
HCA_TO_WAV_KEY_LIST = HCA_TO_WAV_DIR + '\\復号鍵リスト.txt'
